import { UserTableItem } from "./types";

export const USER_PAGE_SIZE = 10;

export const DUMMY_USER_TABLE_ITEMS: UserTableItem[] = [
  {
    id: "1",
    userName: "Sarah Ahmed",
    email: "sarah.ahmed@example.com",
    registrationDate: "2025-11-03",
    status: "active",
    avatar: "https://media.istockphoto.com/id/1465504312/vector/young-smiling-man-avatar-man-with-brown-beard-mustache-and-hair-wearing-yellow-sweater-or.jpg?s=612x612&w=0&k=20&c=9AyNmOwjadmLC1PKpANKEXj56e1KxHj9h9hGknd-Rb0=",
    isBlocked: false,
  },
  {
    id: "2",
    userName: "Noman Rahman",
    email: "noman.rahman@example.com",
    registrationDate: "2025-09-18",
    status: "blocked",
    avatar: "https://media.istockphoto.com/id/1465504312/vector/young-smiling-man-avatar-man-with-brown-beard-mustache-and-hair-wearing-yellow-sweater-or.jpg?s=612x612&w=0&k=20&c=9AyNmOwjadmLC1PKpANKEXj56e1KxHj9h9hGknd-Rb0=",
    isBlocked: true,
  },
  {
    id: "3",
    userName: "Ayesha Khan",
    email: "ayesha.khan@example.com",
    registrationDate: "2025-12-08",
    status: "active",
    avatar: "https://media.istockphoto.com/id/1465504312/vector/young-smiling-man-avatar-man-with-brown-beard-mustache-and-hair-wearing-yellow-sweater-or.jpg?s=612x612&w=0&k=20&c=9AyNmOwjadmLC1PKpANKEXj56e1KxHj9h9hGknd-Rb0=",
    isBlocked: false,
  },
  {
    id: "4",
    userName: "Fahim Islam",
    email: "fahim.islam@example.com",
    registrationDate: "2026-01-12",
    status: "active",
    avatar: "https://media.istockphoto.com/id/1465504312/vector/young-smiling-man-avatar-man-with-brown-beard-mustache-and-hair-wearing-yellow-sweater-or.jpg?s=612x612&w=0&k=20&c=9AyNmOwjadmLC1PKpANKEXj56e1KxHj9h9hGknd-Rb0=",
    isBlocked: false,
  },
  {
    id: "5",
    userName: "Mitu Sultana",
    email: "mitu.sultana@example.com",
    registrationDate: "2026-01-30",
    status: "blocked",
    avatar: "https://media.istockphoto.com/id/1465504312/vector/young-smiling-man-avatar-man-with-brown-beard-mustache-and-hair-wearing-yellow-sweater-or.jpg?s=612x612&w=0&k=20&c=9AyNmOwjadmLC1PKpANKEXj56e1KxHj9h9hGknd-Rb0=",
    isBlocked: true,
  },
  {
    id: "6",
    userName: "Rakib Hasan",
    email: "rakib.hasan@example.com",
    registrationDate: "2026-02-09",
    status: "active",
    avatar: "https://media.istockphoto.com/id/1465504312/vector/young-smiling-man-avatar-man-with-brown-beard-mustache-and-hair-wearing-yellow-sweater-or.jpg?s=612x612&w=0&k=20&c=9AyNmOwjadmLC1PKpANKEXj56e1KxHj9h9hGknd-Rb0=",
    isBlocked: false,
  },
  {
    id: "7",
    userName: "Nabila Noor",
    email: "nabila.noor@example.com",
    registrationDate: "2026-02-14",
    status: "active",
    avatar: "https://media.istockphoto.com/id/1465504312/vector/young-smiling-man-avatar-man-with-brown-beard-mustache-and-hair-wearing-yellow-sweater-or.jpg?s=612x612&w=0&k=20&c=9AyNmOwjadmLC1PKpANKEXj56e1KxHj9h9hGknd-Rb0=",
    isBlocked: false,
  },
  {
    id: "8",
    userName: "Tariq Ahmed",
    email: "tariq.ahmed@example.com",
    registrationDate: "2026-02-20",
    status: "blocked",
    avatar: "https://media.istockphoto.com/id/1465504312/vector/young-smiling-man-avatar-man-with-brown-beard-mustache-and-hair-wearing-yellow-sweater-or.jpg?s=612x612&w=0&k=20&c=9AyNmOwjadmLC1PKpANKEXj56e1KxHj9h9hGknd-Rb0=",
    isBlocked: true,
  },
  {
    id: "9",
    userName: "Adiba Chowdhury",
    email: "adiba.chowdhury@example.com",
    registrationDate: "2026-02-25",
    status: "active",
    avatar: "https://media.istockphoto.com/id/1465504312/vector/young-smiling-man-avatar-man-with-brown-beard-mustache-and-hair-wearing-yellow-sweater-or.jpg?s=612x612&w=0&k=20&c=9AyNmOwjadmLC1PKpANKEXj56e1KxHj9h9hGknd-Rb0=",
    isBlocked: false,
  },
  {
    id: "10",
    userName: "Sabbir Alam",
    email: "sabbir.alam@example.com",
    registrationDate: "2026-03-01",
    status: "active",
    avatar: "https://media.istockphoto.com/id/1465504312/vector/young-smiling-man-avatar-man-with-brown-beard-mustache-and-hair-wearing-yellow-sweater-or.jpg?s=612x612&w=0&k=20&c=9AyNmOwjadmLC1PKpANKEXj56e1KxHj9h9hGknd-Rb0=",
    isBlocked: false,
  },
  {
    id: "11",
    userName: "Rima Akter",
    email: "rima.akter@example.com",
    registrationDate: "2026-03-07",
    status: "blocked",
    avatar: "https://media.istockphoto.com/id/1465504312/vector/young-smiling-man-avatar-man-with-brown-beard-mustache-and-hair-wearing-yellow-sweater-or.jpg?s=612x612&w=0&k=20&c=9AyNmOwjadmLC1PKpANKEXj56e1KxHj9h9hGknd-Rb0=",
    isBlocked: true,
  },
  {
    id: "12",
    userName: "Tanvir Hossain",
    email: "tanvir.hossain@example.com",
    registrationDate: "2026-03-11",
    status: "active",
    avatar: "https://media.istockphoto.com/id/1465504312/vector/young-smiling-man-avatar-man-with-brown-beard-mustache-and-hair-wearing-yellow-sweater-or.jpg?s=612x612&w=0&k=20&c=9AyNmOwjadmLC1PKpANKEXj56e1KxHj9h9hGknd-Rb0=",
    isBlocked: false,
  },
];
