import { AdminBagItem } from "./types";

export const ADMIN_BAG_PAGE_SIZE = 10;

export const DUMMY_ADMIN_BAGS: AdminBagItem[] = [
  {
    id: "AB-001",
    brandId: "brand-001",
    modelId: "model-001",
    bagImage: "https://i.postimg.cc/Px6KY2s9/Frame-2147241971.png",
    brand: "Hermes",
    model: "Birkin 30",
    bagColor: "Gold",
    leatherType: "Togo",
    hardwareColor: "Palladium",
    size: "30",
    condition: "Excellent",
    productionYear: 2025,
    currentValue: 18750,
  },
  {
    id: "AB-002",
    brandId: "brand-002",
    modelId: "model-002",
    bagImage: "https://i.postimg.cc/Px6KY2s9/Frame-2147241971.png",
    brand: "Chanel",
    model: "Classic Flap",
    bagColor: "Black",
    leatherType: "Caviar",
    hardwareColor: "Gold",
    size: "Medium",
    condition: "Very Good",
    productionYear: 2024,
    currentValue: 14600,
  },
  {
    id: "AB-003",
    brandId: "brand-003",
    modelId: "model-003",
    bagImage: "https://i.postimg.cc/Px6KY2s9/Frame-2147241971.png",
    brand: "Dior",
    model: "Lady Dior",
    bagColor: "Rose",
    leatherType: "Lambskin",
    hardwareColor: "Gold",
    size: "Small",
    condition: "Excellent",
    productionYear: 2023,
    currentValue: 11200,
  },
  {
    id: "AB-004",
    brandId: "brand-004",
    modelId: "model-004",
    bagImage: "https://i.postimg.cc/Px6KY2s9/Frame-2147241971.png",
    brand: "Gucci",
    model: "Jackie 1961",
    bagColor: "Brown",
    leatherType: "Calfskin",
    hardwareColor: "Silver",
    size: "Small",
    condition: "Good",
    productionYear: 2022,
    currentValue: 6900,
  },
  {
    id: "AB-005",
    brandId: "brand-005",
    modelId: "model-005",
    bagImage: "https://i.postimg.cc/Px6KY2s9/Frame-2147241971.png",
    brand: "Louis Vuitton",
    model: "Capucines",
    bagColor: "Cream",
    leatherType: "Taurillon",
    hardwareColor: "Gold",
    size: "BB",
    condition: "Excellent",
    productionYear: 2025,
    currentValue: 9800,
  },
  {
    id: "AB-006",
    brandId: "brand-006",
    modelId: "model-006",
    bagImage: "https://i.postimg.cc/Px6KY2s9/Frame-2147241971.png",
    brand: "Loewe",
    model: "Puzzle",
    bagColor: "Tan",
    leatherType: "Classic Calfskin",
    hardwareColor: "Silver",
    size: "Small",
    condition: "Good",
    productionYear: 2021,
    currentValue: 5400,
  },
  {
    id: "AB-007",
    brandId: "brand-007",
    modelId: "model-007",
    bagImage: "https://i.postimg.cc/Px6KY2s9/Frame-2147241971.png",
    brand: "YSL",
    model: "Le 5 a 7",
    bagColor: "Black",
    leatherType: "Smooth Leather",
    hardwareColor: "Bronze",
    size: "Standard",
    condition: "Very Good",
    productionYear: 2024,
    currentValue: 5100,
  },
  {
    id: "AB-008",
    brandId: "brand-008",
    modelId: "model-008",
    bagImage: "https://i.postimg.cc/Px6KY2s9/Frame-2147241971.png",
    brand: "Bottega Veneta",
    model: "Cassette",
    bagColor: "Parakeet",
    leatherType: "Intrecciato Leather",
    hardwareColor: "Gold",
    size: "Mini",
    condition: "Excellent",
    productionYear: 2023,
    currentValue: 6700,
  },
  {
    id: "AB-009",
    brandId: "brand-009",
    modelId: "model-009",
    bagImage: "https://i.postimg.cc/Px6KY2s9/Frame-2147241971.png",
    brand: "Fendi",
    model: "Baguette",
    bagColor: "Purple",
    leatherType: "Nappa",
    hardwareColor: "Silver",
    size: "Standard",
    condition: "Good",
    productionYear: 2020,
    currentValue: 4300,
  },
  {
    id: "AB-010",
    brandId: "brand-010",
    modelId: "model-010",
    bagImage: "https://i.postimg.cc/Px6KY2s9/Frame-2147241971.png",
    brand: "Balenciaga",
    model: "Rodeo",
    bagColor: "Grey",
    leatherType: "Arena Leather",
    hardwareColor: "Silver",
    size: "Medium",
    condition: "Excellent",
    productionYear: 2025,
    currentValue: 6200,
  },
  {
    id: "AB-011",
    brandId: "brand-011",
    modelId: "model-011",
    bagImage: "https://i.postimg.cc/Px6KY2s9/Frame-2147241971.png",
    brand: "Prada",
    model: "Galleria",
    bagColor: "Pink",
    leatherType: "Saffiano",
    hardwareColor: "Gold",
    size: "Medium",
    condition: "Very Good",
    productionYear: 2022,
    currentValue: 5900,
  },
  {
    id: "AB-012",
    brandId: "brand-012",
    modelId: "model-012",
    bagImage: "https://i.postimg.cc/Px6KY2s9/Frame-2147241971.png",
    brand: "Celine",
    model: "Triomphe",
    bagColor: "Tan",
    leatherType: "Shiny Calfskin",
    hardwareColor: "Gold",
    size: "Teen",
    condition: "Excellent",
    productionYear: 2021,
    currentValue: 6100,
  },
];
